/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDeliveriesRouteImport } from './routes/_app/deliveries'
import { Route as AppIntakeSimulatorRouteImport } from './routes/_app/intake-simulator'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppRoutingRouteImport } from './routes/_app/routing'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads.index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads.$leadId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1IntakeLeadsRouteImport } from './routes/api/v1/intake/leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeSimulatorRoute = AppIntakeSimulatorRouteImport.update({
  id: '/intake-simulator',
  path: '/intake-simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IntakeLeadsRoute = ApiV1IntakeLeadsRouteImport.update({
  id: '/api/v1/intake/leads',
  path: '/api/v1/intake/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/ready': typeof ReadyRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliveries': typeof AppDeliveriesRoute
  '/intake-simulator': typeof AppIntakeSimulatorRoute
  '/integrations': typeof AppIntegrationsRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/api/v1/intake/leads': typeof ApiV1IntakeLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/ready': typeof ReadyRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliveries': typeof AppDeliveriesRoute
  '/intake-simulator': typeof AppIntakeSimulatorRoute
  '/integrations': typeof AppIntegrationsRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/leads': typeof AppLeadsIndexRoute
  '/api/v1/intake/leads': typeof ApiV1IntakeLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/ready': typeof ReadyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deliveries': typeof AppDeliveriesRoute
  '/_app/intake-simulator': typeof AppIntakeSimulatorRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/routing': typeof AppRoutingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/api/v1/intake/leads': typeof ApiV1IntakeLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/ready'
    | '/dashboard'
    | '/deliveries'
    | '/intake-simulator'
    | '/integrations'
    | '/leads'
    | '/routing'
    | '/settings'
    | '/leads/$leadId'
    | '/api/auth/$'
    | '/leads/'
    | '/api/v1/intake/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/ready'
    | '/dashboard'
    | '/deliveries'
    | '/intake-simulator'
    | '/integrations'
    | '/routing'
    | '/settings'
    | '/leads/$leadId'
    | '/api/auth/$'
    | '/leads'
    | '/api/v1/intake/leads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/health'
    | '/login'
    | '/ready'
    | '/_app/dashboard'
    | '/_app/deliveries'
    | '/_app/intake-simulator'
    | '/_app/integrations'
    | '/_app/leads'
    | '/_app/routing'
    | '/_app/settings'
    | '/_app/leads/$leadId'
    | '/api/auth/$'
    | '/_app/leads/'
    | '/api/v1/intake/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ReadyRoute: typeof ReadyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1IntakeLeadsRoute: typeof ApiV1IntakeLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries': {
      id: '/_app/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake-simulator': {
      id: '/_app/intake-simulator'
      path: '/intake-simulator'
      fullPath: '/intake-simulator'
      preLoaderRoute: typeof AppIntakeSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing': {
      id: '/_app/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/intake/leads': {
      id: '/api/v1/intake/leads'
      path: '/api/v1/intake/leads'
      fullPath: '/api/v1/intake/leads'
      preLoaderRoute: typeof ApiV1IntakeLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveriesRoute: typeof AppDeliveriesRoute
  AppIntakeSimulatorRoute: typeof AppIntakeSimulatorRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppRoutingRoute: typeof AppRoutingRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveriesRoute: AppDeliveriesRoute,
  AppIntakeSimulatorRoute: AppIntakeSimulatorRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppRoutingRoute: AppRoutingRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ReadyRoute: ReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1IntakeLeadsRoute: ApiV1IntakeLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
