"""Fictional demo leads, integrations, and routing rules.

All contacts and companies are fictional. CRM destinations are sandbox adapters.
"""

from __future__ import annotations

from typing import Any

SEED_INTEGRATIONS: list[dict[str, Any]] = [
    {
        "provider": "hubspot",
        "name": "HubSpot Sandbox",
        "success": 8,
        "fail": 0,
        "public_id": "INT-HUB",
    },
    {
        "provider": "pipedrive",
        "name": "Pipedrive Sandbox",
        "success": 3,
        "fail": 0,
        "public_id": "INT-PD",
    },
    {
        "provider": "zoho",
        "name": "Zoho CRM Sandbox",
        "success": 4,
        "fail": 0,
        "public_id": "INT-ZOHO",
    },
    {
        "provider": "webhook",
        "name": "Default CRM Sandbox",
        "success": 5,
        "fail": 2,
        "public_id": "INT-WH",
    },
]

SEED_RULES: list[dict[str, Any]] = [
    {
        "name": "Enterprise CRM projects",
        "priority": 10,
        "field": "budget",
        "operator": "greater_than",
        "comparison_value": "4999.99",
        "provider": "hubspot",
        "stop_processing": True,
    },
    {
        "name": "United Kingdom leads",
        "priority": 20,
        "field": "country",
        "operator": "equals",
        "comparison_value": "GB",
        "provider": "pipedrive",
        "stop_processing": True,
    },
    {
        "name": "Business automation requests",
        "priority": 30,
        "field": "service",
        "operator": "contains",
        "comparison_value": "automation",
        "provider": "zoho",
        "stop_processing": True,
    },
    {
        "name": "Default catch-all",
        "priority": 100,
        "field": "email",
        "operator": "is_not_empty",
        "comparison_value": None,
        "provider": "webhook",
        "stop_processing": True,
    },
]

SEED_LEADS: list[dict[str, Any]] = [
    {
        "first_name": "Maya",
        "last_name": "Chen",
        "email": "maya.chen@example.com",
        "phone": "+44 20 7946 0958",
        "company": "Northstar Studio",
        "job_title": "Operations Manager",
        "country": "GB",
        "service": "CRM integration",
        "budget": 8500,
        "currency": "USD",
        "message": "We need to connect three website forms to our CRM and preserve campaign attribution.",
        "source": "website",
        "utm_source": "google",
        "utm_medium": "cpc",
        "utm_campaign": "crm_automation_q3",
        "external_id": "FORM-10482",
        "days_ago": 1,
        "hours": 10,
        "delivery": "delivered",
    },
    {
        "first_name": "James",
        "last_name": "Whitfield",
        "email": "james.whitfield@example.com",
        "phone": "+1 415 555 0142",
        "company": "Helio Analytics",
        "job_title": "Director of Revenue Operations",
        "country": "US",
        "service": "CRM integration",
        "budget": 14000,
        "currency": "USD",
        "message": "Looking for a durable intake layer between six product sites and HubSpot.",
        "source": "webinar",
        "utm_source": "linkedin",
        "utm_medium": "social",
        "utm_campaign": "revops_webinar",
        "external_id": "WEB-2201",
        "days_ago": 2,
        "hours": 15,
        "delivery": "delivered",
    },
    {
        "first_name": "Priya",
        "last_name": "Nair",
        "email": "priya.nair@example.com",
        "phone": "+91 80 4567 2210",
        "company": "Brightline Ops",
        "job_title": "Head of Automation",
        "country": "IN",
        "service": "Business automation",
        "budget": 3900,
        "currency": "USD",
        "message": "Need routing rules for inbound demo requests from APAC landing pages.",
        "source": "website",
        "utm_source": "google",
        "utm_medium": "organic",
        "utm_campaign": "automation_guide",
        "external_id": "FORM-11820",
        "days_ago": 3,
        "hours": 8,
        "delivery": "delivered",
    },
    {
        "first_name": "Oliver",
        "last_name": "Grant",
        "email": "oliver.grant@example.com",
        "phone": "+44 161 496 0288",
        "company": "Thames Digital",
        "job_title": "Marketing Operations Lead",
        "country": "GB",
        "service": "Website forms",
        "budget": 2400,
        "currency": "USD",
        "message": "UK website forms currently dump into a shared inbox. We want Pipedrive.",
        "source": "partner",
        "external_id": "PARTNER-44",
        "days_ago": 4,
        "hours": 11,
        "delivery": "delivered",
    },
    {
        "first_name": "Sofia",
        "last_name": "Alvarez",
        "email": "sofia.alvarez@example.com",
        "phone": "+34 91 123 4580",
        "company": "Campo Norte",
        "job_title": "COO",
        "country": "ES",
        "service": "CRM integration",
        "budget": 7200,
        "currency": "USD",
        "message": "Connecting event registrations and outbound sequences into one pipeline.",
        "source": "website",
        "utm_source": "bing",
        "utm_medium": "cpc",
        "utm_campaign": "iberia_crm",
        "external_id": "FORM-3301",
        "days_ago": 5,
        "hours": 9,
        "delivery": "delivered",
    },
    {
        "first_name": "Henrik",
        "last_name": "Larsen",
        "email": "henrik.larsen@example.com",
        "phone": "+47 21 55 12 90",
        "company": "Fjord Systems",
        "job_title": "IT Manager",
        "country": "NO",
        "service": "Business automation",
        "budget": 4100,
        "currency": "USD",
        "message": "We want webhook automation for partner-sourced leads.",
        "source": "inbound",
        "external_id": "INB-902",
        "days_ago": 6,
        "hours": 14,
        "delivery": "delivered",
    },
    {
        "first_name": "Amina",
        "last_name": "Diallo",
        "email": "amina.diallo@example.com",
        "phone": "+27 21 555 0199",
        "company": "Harbor Collective",
        "job_title": "Founder",
        "country": "ZA",
        "service": "Lead capture",
        "budget": 1800,
        "currency": "USD",
        "message": "Small studio looking to stop losing form submissions.",
        "source": "website",
        "external_id": "FORM-4410",
        "days_ago": 2,
        "hours": 18,
        "delivery": "failed",
        "force_fail": True,
    },
    {
        "first_name": "Kenji",
        "last_name": "Mori",
        "email": "kenji.mori@example.com",
        "phone": "+81 3 1234 7788",
        "company": "Shibuya Labs",
        "job_title": "Product Operations",
        "country": "JP",
        "service": "Data migration",
        "budget": 9600,
        "currency": "USD",
        "message": "Need a migration path from spreadsheets into a CRM with attribution intact.",
        "source": "linkedin",
        "utm_source": "linkedin",
        "utm_medium": "paid",
        "utm_campaign": "apac_migration",
        "external_id": "LI-1882",
        "days_ago": 7,
        "hours": 7,
        "delivery": "delivered",
    },
    {
        "first_name": "Claire",
        "last_name": "Dubois",
        "email": "claire.dubois@example.com",
        "phone": "+33 1 42 68 5301",
        "company": "Atelier Nord",
        "job_title": "Revenue Manager",
        "country": "FR",
        "service": "Business automation",
        "budget": 2600,
        "currency": "USD",
        "message": "Automate assignment of inbound demo requests by language and region.",
        "source": "referral",
        "external_id": "REF-77",
        "days_ago": 8,
        "hours": 12,
        "delivery": "delivered",
    },
    {
        "first_name": "Ryan",
        "last_name": "O'Connell",
        "email": "ryan.oconnell@example.com",
        "phone": "+353 1 555 0144",
        "company": "Liffey Software",
        "job_title": "Growth Lead",
        "country": "IE",
        "service": "Website forms",
        "budget": 1500,
        "currency": "USD",
        "message": "Two marketing sites, one CRM. Forms currently go nowhere useful.",
        "source": "website",
        "external_id": "FORM-5521",
        "days_ago": 0,
        "hours": 2,
        "delivery": "queued",
    },
    {
        "first_name": "Nina",
        "last_name": "Berg",
        "email": "nina.berg@example.com",
        "phone": "+31 20 555 0188",
        "company": "Canalstraat Studio",
        "job_title": "Operations Director",
        "country": "NL",
        "service": "CRM integration",
        "budget": 5500,
        "currency": "USD",
        "message": "Need HubSpot-ready payloads from Typeform and a custom site.",
        "source": "webinar",
        "utm_source": "email",
        "utm_medium": "nurture",
        "utm_campaign": "benelux_ops",
        "external_id": "WEB-441",
        "days_ago": 9,
        "hours": 16,
        "delivery": "delivered",
    },
    {
        "first_name": "Tomasz",
        "last_name": "Kowalski",
        "email": "tomasz.kowalski@example.com",
        "phone": "+48 22 555 0190",
        "company": "Baltic Grid",
        "job_title": "Support Lead",
        "country": "PL",
        "service": "Customer support tooling",
        "budget": 900,
        "currency": "USD",
        "message": "Exploring a light-weight lead intake for a regional support team.",
        "source": "inbound",
        "external_id": "INB-331",
        "days_ago": 3,
        "hours": 20,
        "delivery": "failed",
        "force_fail": True,
    },
    {
        "first_name": "Emily",
        "last_name": "Walsh",
        "email": "emily.walsh@example.com",
        "phone": "+1 617 555 0194",
        "company": "Redwood Retail",
        "job_title": "CRM Administrator",
        "country": "US",
        "service": "Website forms",
        "budget": 4800,
        "currency": "USD",
        "message": "Replace Zapier with something we can audit and retry.",
        "source": "website",
        "utm_source": "google",
        "utm_medium": "cpc",
        "utm_campaign": "ops_tooling",
        "external_id": "FORM-9001",
        "days_ago": 10,
        "hours": 13,
        "delivery": "delivered",
    },
    {
        "first_name": "Maya",
        "last_name": "Chen",
        "email": "maya.chen@example.com",
        "phone": "+44 20 7946 1100",
        "company": "Northstar Studio",
        "job_title": "Operations Manager",
        "country": "GB",
        "service": "CRM integration",
        "budget": 8500,
        "currency": "USD",
        "message": "Second submission from the pricing page.",
        "source": "website",
        "utm_source": "google",
        "utm_medium": "cpc",
        "utm_campaign": "crm_automation_q3",
        "external_id": "FORM-10499",
        "days_ago": 1,
        "hours": 6,
        "delivery": "delivered",
        "duplicate_of": 0,
        "duplicate_reason": "normalized_email",
    },
    {
        "first_name": "Ollie",
        "last_name": "Grant",
        "email": "o.grant@thamesdigital.example",
        "phone": "+44 161 496 0288",
        "company": "Thames Digital",
        "job_title": "Marketing Operations Lead",
        "country": "GB",
        "service": "Website forms",
        "budget": 2400,
        "currency": "USD",
        "message": "Follow-up from the partner portal using a different email.",
        "source": "partner",
        "external_id": "PARTNER-45",
        "days_ago": 3,
        "hours": 17,
        "delivery": "delivered",
        "duplicate_of": 3,
        "duplicate_reason": "normalized_phone",
    },
    {
        "first_name": "Lucas",
        "last_name": "Ferreira",
        "email": "lucas.ferreira@example.com",
        "phone": "+351 21 555 0177",
        "company": "Lisbon Stack",
        "job_title": "COO",
        "country": "PT",
        "service": "Business automation",
        "budget": 3300,
        "currency": "USD",
        "message": "Automate partner and inbound leads into one owner queue.",
        "source": "partner",
        "external_id": "PARTNER-91",
        "days_ago": 11,
        "hours": 10,
        "delivery": "delivered",
    },
    {
        "first_name": "Sara",
        "last_name": "Lindqvist",
        "email": "sara.lindqvist@example.com",
        "phone": "+46 8 555 0122",
        "company": "Norrsken Apps",
        "job_title": "Head of Growth",
        "country": "SE",
        "service": "CRM integration",
        "budget": 11200,
        "currency": "USD",
        "message": "Enterprise CRM project across four brands. Attribution is non-negotiable.",
        "source": "website",
        "utm_source": "google",
        "utm_medium": "cpc",
        "utm_campaign": "nordics_enterprise",
        "external_id": "FORM-7004",
        "days_ago": 12,
        "hours": 9,
        "delivery": "delivered",
    },
    {
        "first_name": "Daniel",
        "last_name": "Cho",
        "email": "daniel.cho@example.com",
        "phone": "+65 6555 0193",
        "company": "Meridian Cloud",
        "job_title": "Solutions Architect",
        "country": "SG",
        "service": "Data migration",
        "budget": 6700,
        "currency": "USD",
        "message": "Moving historical leads from a legacy CSV dump without losing source.",
        "source": "linkedin",
        "utm_source": "linkedin",
        "utm_medium": "sponsored",
        "utm_campaign": "sea_migration",
        "external_id": "LI-440",
        "days_ago": 13,
        "hours": 11,
        "delivery": "delivered",
    },
    {
        "first_name": "Hannah",
        "last_name": "Brooks",
        "email": "hannah.brooks@example.com",
        "phone": "+1 416 555 0160",
        "company": "Maple & Pine",
        "job_title": "Operations Coordinator",
        "country": "CA",
        "service": "Lead capture",
        "budget": 2200,
        "currency": "USD",
        "message": "Need a retry-capable webhook for the careers and contact forms.",
        "source": "website",
        "external_id": "FORM-2219",
        "days_ago": 0,
        "hours": 4,
        "delivery": "queued",
    },
    {
        "first_name": "Matteo",
        "last_name": "Ricci",
        "email": "matteo.ricci@example.com",
        "phone": "+39 02 555 0166",
        "company": "Quattro Forme",
        "job_title": "Digital Operations",
        "country": "IT",
        "service": "Business automation",
        "budget": 4400,
        "currency": "USD",
        "message": "Route Italian and English forms to different owners automatically.",
        "source": "webinar",
        "utm_source": "email",
        "utm_medium": "invite",
        "utm_campaign": "milan_ops",
        "external_id": "WEB-118",
        "days_ago": 6,
        "hours": 19,
        "delivery": "delivered",
    },
    {
        "first_name": "Grace",
        "last_name": "Adeyemi",
        "email": "grace.adeyemi@example.com",
        "phone": "+27 11 555 0133",
        "company": "Cape Route",
        "job_title": "Managing Partner",
        "country": "ZA",
        "service": "CRM integration",
        "budget": 8000,
        "currency": "USD",
        "message": "Three regional sites, one CRM, strict duplicate handling.",
        "source": "website",
        "utm_source": "google",
        "utm_medium": "cpc",
        "utm_campaign": "africa_crm",
        "external_id": "FORM-8120",
        "days_ago": 4,
        "hours": 8,
        "delivery": "delivered",
    },
    {
        "first_name": "Ben",
        "last_name": "Hart",
        "email": "ben.hart@example.com",
        "phone": "+61 2 5550 1788",
        "company": "Dockside Analytics",
        "job_title": "RevOps Analyst",
        "country": "AU",
        "service": "Lead capture",
        "budget": 1100,
        "currency": "USD",
        "message": "Simple intake with source tracking for a consulting site.",
        "source": "referral",
        "external_id": "REF-12",
        "days_ago": 8,
        "hours": 5,
        "delivery": "delivered",
    },
]
